name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust if needed

    - name: Install dependencies
      run: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r hello_app/requirements.txt  # Adjust path to requirements

    - name: Archive Files
      run: |
        zip -r app_package.zip hello_app startup.py requirements.txt  # Package app files

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-package
        path: app_package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: app-package

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApp-Python-Flask-RG-Devansh-POC'                # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: './app_package.zip'
        startup-command: 'gunicorn -w 4 -b 0.0.0.0:8000 startup:app'  # Startup command for Gunicorn
