name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive Files
      run: |
        zip -r app_package.zip hello_app startup.py requirements.txt

    - name: Upload Artifact (Workaround)
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Content-Type: application/zip" \
        --data-binary @"app_package.zip" \
        "https://api.github.com/repos/${{ github.repository }}/releases/latest/assets?name=app-package.zip"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifact via Curl
      run: |
            curl -L -o app_package.zip \
            "https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts"


    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApp-Python-Flask-RG-Devansh-POC'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: './app_package.zip'
        startup-command: 'gunicorn -w 4 -b 0.0.0.0:8000 startup:app'
