name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApp-Python-Flask-RG-Devansh-POC'       # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: '.'                      # Deploy the entire repository (adjust if needed)
